### ISSUE TITLE
Toasty.js not loading

### ISSUE THREAD

**Issue by anandSug** [egalink/Toasty.js#2]
I downloaded the zip and extracted the code to my code base and added it to the main.php 
`<link href="/admin/js/Toasty/dist/toasty.min.css" rel="stylesheet">
 <script src="/admin/js/Toasty/dist/toasty.min.js"></script>`

I even tried importing the toasty.css and toasty.js. 

But I keep getting the same error in the console:
`Uncaught TypeError: Cannot read property 'childNodes' of null`

Any help is much appreciated.

**Comment by HusseinElGanzory** [comment]
i set the javascript refrenece toast.min.js at end of the html file it working well
